 spring:
   datasource:
      url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/hanagreenworld?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
      username: ${DATASOURCE_USERNAME:root}
      password: ${DATASOURCE_PASSWORD:password}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 300000
        max-lifetime: 1200000
        connection-timeout: 20000
        leak-detection-threshold: 60000